language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sakuffo/frontend-app -f Dockerfile.dev .

script:
  - docker run -e CI=true sakuffo/frontend-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend-app"
  env: "Frontendapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-981894193627"
  bucket_path: "frontend-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"